-- ============================================================
-- seed.sql — reference data: habit_catalog + badge_definitions
-- Trilingual (ar/en/fr). Run via `supabase db reset`.
-- ============================================================

-- ---------- BADGE DEFINITIONS (streak shields + more) ----------
insert into public.badge_definitions (key, tier, category, title, description, icon, criteria_type, threshold, sort_order) values
('first_log','bronze','milestone',
  '{"ar":"أول خطوة","en":"First Step","fr":"Premier pas"}',
  '{"ar":"سجّلت أول يوم — البداية أصعب خطوة 🌱","en":"You logged your first day.","fr":"Vous avez enregistré votre premier jour."}',
  '🌱','first_log',1,1),
('streak_3','bronze','streak',
  '{"ar":"٣ أيام متتالية","en":"3-Day Streak","fr":"Série de 3 jours"}',
  '{"ar":"العادة بدأت تتشكّل — استمر 💪","en":"The habit is forming.","fr":"L''habitude se forme."}',
  '💪','streak_clean_days',3,2),
('streak_7','bronze','streak',
  '{"ar":"أسبوع كامل","en":"One Week","fr":"Une semaine"}',
  '{"ar":"أسبوع بلا تعثّر — الدماغ يتغيّر ⭐","en":"A full clean week.","fr":"Une semaine complète."}',
  '⭐','streak_clean_days',7,3),
('streak_14','bronze','streak',
  '{"ar":"أسبوعان","en":"Two Weeks","fr":"Deux semaines"}',
  '{"ar":"إنجاز حقيقي — الدائرة العصبية تتبدّل","en":"Two weeks strong.","fr":"Deux semaines."}',
  '🔥','streak_clean_days',14,4),
('streak_30_silver','silver','streak',
  '{"ar":"درع فضي — ٣٠ يوم","en":"Silver Shield — 30 Days","fr":"Bouclier argent — 30 jours"}',
  '{"ar":"شهر كامل! إنجاز يستحق الفخر 🥈","en":"A full month — proud of you!","fr":"Un mois entier !"}',
  '🥈','streak_clean_days',30,5),
('streak_60_gold','gold','streak',
  '{"ar":"درع ذهبي — ٦٠ يوم","en":"Gold Shield — 60 Days","fr":"Bouclier or — 60 jours"}',
  '{"ar":"شهران متتاليان — أنت في مرحلة متقدمة 🥇","en":"Two months in a row!","fr":"Deux mois d''affilée !"}',
  '🥇','streak_clean_days',60,6),
('streak_90_diamond','diamond','streak',
  '{"ar":"درع ماسي — ٩٠ يوم","en":"Diamond Shield — 90 Days","fr":"Bouclier diamant — 90 jours"}',
  '{"ar":"٩٠ يوم! العادة الجديدة أصبحت جزءاً منك 💎","en":"90 days — a new you!","fr":"90 jours — un nouveau vous !"}',
  '💎','streak_clean_days',90,7),
('streak_180_diamond','diamond','streak',
  '{"ar":"ماسة الصبر — ١٨٠ يوم","en":"Patience Diamond — 180 Days","fr":"Diamant patience — 180 jours"}',
  '{"ar":"نصف عام من الثبات — مَثَل يُحتذى","en":"Half a year of consistency.","fr":"Six mois de constance."}',
  '💎','streak_clean_days',180,8),
('comeback','special','recovery',
  '{"ar":"العودة أقوى","en":"Stronger Comeback","fr":"Retour plus fort"}',
  '{"ar":"تعثّرت ورجعت — ده عين النجاح 🤍","en":"You stumbled and came back.","fr":"Vous êtes revenu plus fort."}',
  '🤍','comeback_after_relapse',1,9),
('logged_30','silver','consistency',
  '{"ar":"مواظب — ١٠٠ تسجيلة","en":"Consistent — 100 Logs","fr":"Assidu — 100 journaux"}',
  '{"ar":"١٠٠ يوم من المتابعة المنتظمة","en":"100 days of tracking.","fr":"100 jours de suivi."}',
  '📈','days_logged',100,10);

-- ---------- HABIT CATALOG ----------
-- BREAK track
insert into public.habit_catalog (key, track, category, title, description, icon, default_template_key, is_islamic, islamweb_ref, popularity, sort_order) values
('quit_smoking','break','health',
  '{"ar":"الإقلاع عن التدخين","en":"Quit smoking","fr":"Arrêter de fumer"}',
  '{"ar":"تحرّر من السجائر خطوة بخطوة","en":"Break free from cigarettes.","fr":"Libérez-vous de la cigarette."}',
  '🚭','hrt_8week',false,'https://www.islamweb.net/ar/fatwa/4257/', 100, 1),
('quit_vaping','break','health',
  '{"ar":"ترك الفيب","en":"Quit vaping","fr":"Arrêter la vape"}',
  '{"ar":"توقّف عن التدخين الإلكتروني","en":"Stop e-cigarettes.","fr":"Arrêtez l''e-cigarette."}',
  '💨','hrt_8week',false,null, 70, 2),
('nail_biting','break','mind',
  '{"ar":"قضم الأظافر","en":"Nail biting","fr":"Rongement des ongles"}',
  '{"ar":"عادة عصبية شائعة — نتعامل معها بوعي","en":"A common nervous habit.","fr":"Une habitude nerveuse courante."}',
  '💅','hrt_8week',false,null, 80, 3),
('hair_pulling','break','mind',
  '{"ar":"متلازمة نتف الشعر","en":"Hair pulling (Trichotillomania)","fr":"Trichotillomanie (arrachage des cheveux)"}',
  '{"ar":"متابعة بمنهج HRT العلمي","en":"Tracked with the evidence-based HRT method.","fr":"Suivi avec la méthode HRT."}',
  '💇','hrt_8week',false,null, 60, 4),
('skin_picking','break','mind',
  '{"ar":"نتش الجلد","en":"Skin picking","fr":"Grattage de la peau"}',
  '{"ar":"عادة جلدية متكررة — نخفّفها بالتدريب","en":"A repetitive skin habit.","fr":"Une habitude cutanée répétitive."}',
  '🤚','hrt_8week',false,null, 40, 5),
('secret_habit','break','mind',
  '{"ar":"العادة السرية","en":"Compulsive masturbation","fr":"Masturbation compulsive"}',
  '{"ar":"تحرّر بثبات وستر، بمنهج علمي وروح داعمة","en":"Break free with discretion and support.","fr":"Libérez-vous avec discrétion et soutien."}',
  '🔒','hrt_8week',true,null, 90, 6),
('phone_addiction','break','productivity',
  '{"ar":"إدمان الهاتف","en":"Phone addiction","fr":"Addiction au téléphone"}',
  '{"ar":"قلّل التصفّح اللاواعي واسترجع وقتك","en":"Reclaim your time from doomscrolling.","fr":"Reprenez votre temps."}',
  '📱','generic',false,null, 95, 6),
('excessive_gaming','break','productivity',
  '{"ar":"الإفراط في الألعاب","en":"Excessive gaming","fr":"Jeux excessifs"}',
  '{"ar":"توازن أفضل مع الألعاب","en":"Find a healthier balance.","fr":"Trouvez l''équilibre."}',
  '🎮','generic',false,null, 55, 7),
('procrastination','break','productivity',
  '{"ar":"التسويف والمماطلة","en":"Procrastination","fr":"Procrastination"}',
  '{"ar":"ابدأ بدلاً من التأجيل","en":"Start instead of postponing.","fr":"Commencez au lieu de reporter."}',
  '⏳','generic',false,null, 85, 8),
('junk_food','break','health',
  '{"ar":"الأكل غير الصحي","en":"Junk food","fr":"Malbouffe"}',
  '{"ar":"قلّل السكر والوجبات السريعة","en":"Cut sugar and fast food.","fr":"Réduisez le sucre."}',
  '🍔','generic',false,null, 75, 9),
('oversleeping','break','health',
  '{"ar":"كثرة النوم","en":"Oversleeping","fr":"Trop dormir"}',
  '{"ar":"نظّم نومك واستيقظ بنشاط","en":"Regulate your sleep.","fr":"Régulez votre sommeil."}',
  '😴','generic',false,null, 50, 10),
('gossip','break','social',
  '{"ar":"الغيبة والنميمة","en":"Gossip & backbiting","fr":"Médisance"}',
  '{"ar":"احفظ لسانك — خير لك في دينك ودنياك","en":"Guard your tongue.","fr":"Préservez votre langue."}',
  '🤐','generic',true,'https://www.islamweb.net/ar/fatwa/1531/', 45, 11),
('bad_language','break','social',
  '{"ar":"الألفاظ السيّئة","en":"Bad language","fr":"Langage grossier"}',
  '{"ar":"كلام طيّب وأخلاق أحسن","en":"Cleaner, kinder speech.","fr":"Un langage plus doux."}',
  '🗯️','generic',true,null, 35, 12),
('impulse_buying','break','productivity',
  '{"ar":"الشراء الاندفاعي","en":"Impulse buying","fr":"Achats impulsifs"}',
  '{"ar":"قرارات إنفاق أوعى","en":"Smarter spending decisions.","fr":"Des dépenses plus réfléchies."}',
  '🛍️','generic',false,null, 40, 13),
('caffeine_excess','break','health',
  '{"ar":"الإفراط في الكافيين","en":"Too much caffeine","fr":"Excès de caféine"}',
  '{"ar":"قلّل القهوة ومشروبات الطاقة","en":"Cut back on coffee/energy drinks.","fr":"Réduisez la caféine."}',
  '☕','generic',false,null, 38, 14);

-- BUILD track
insert into public.habit_catalog (key, track, category, title, description, icon, default_template_key, is_islamic, islamweb_ref, popularity, sort_order) values
('pray_on_time','build','worship',
  '{"ar":"المحافظة على الصلاة في وقتها","en":"Pray on time","fr":"Prier à l''heure"}',
  '{"ar":"عماد الدين — حافظ على صلواتك الخمس","en":"Keep the five daily prayers on time.","fr":"Les cinq prières à l''heure."}',
  '🕌','generic',true,'https://www.islamweb.net/ar/fatwa/13619/', 100, 20),
('daily_quran','build','worship',
  '{"ar":"وِرد القرآن اليومي","en":"Daily Qur''an","fr":"Coran quotidien"}',
  '{"ar":"اجعل لك وِرداً ثابتاً من كتاب الله","en":"A steady daily portion of Qur''an.","fr":"Une portion quotidienne du Coran."}',
  '📖','generic',true,null, 95, 21),
('adhkar','build','worship',
  '{"ar":"أذكار الصباح والمساء","en":"Morning & evening adhkar","fr":"Adhkar matin et soir"}',
  '{"ar":"حصّن يومك بالذكر","en":"Fortify your day with remembrance.","fr":"Protégez votre journée."}',
  '📿','generic',true,null, 90, 22),
('voluntary_fasting','build','worship',
  '{"ar":"صيام النوافل","en":"Voluntary fasting","fr":"Jeûne surérogatoire"}',
  '{"ar":"الاثنين والخميس والأيام البيض","en":"Mondays, Thursdays, white days.","fr":"Lundi, jeudi, jours blancs."}',
  '🌙','generic',true,'https://www.islamweb.net/ar/fatwa/50964/', 70, 23),
('qiyam','build','worship',
  '{"ar":"قيام الليل","en":"Night prayer (Qiyam)","fr":"Prière de nuit"}',
  '{"ar":"شرف المؤمن قيامه بالليل","en":"The honor of the believer.","fr":"L''honneur du croyant."}',
  '🌌','generic',true,null, 65, 24),
('keeping_ties','build','social',
  '{"ar":"صلة الرحم","en":"Keeping family ties","fr":"Liens familiaux"}',
  '{"ar":"تواصل مع أهلك وقرابتك","en":"Stay connected with your kin.","fr":"Restez en lien avec vos proches."}',
  '🤝','generic',true,null, 60, 25),
('daily_charity','build','worship',
  '{"ar":"صدقة يومية","en":"Daily charity","fr":"Aumône quotidienne"}',
  '{"ar":"ولو بالقليل — الصدقة تطفئ الخطيئة","en":"Even a little, every day.","fr":"Même peu, chaque jour."}',
  '💝','generic',true,null, 58, 26),
('istighfar','build','worship',
  '{"ar":"الاستغفار اليومي","en":"Daily istighfar","fr":"Istighfar quotidien"}',
  '{"ar":"عوّد لسانك على الاستغفار","en":"Keep your tongue moist with istighfar.","fr":"Habituez votre langue à l''istighfar."}',
  '🤲','generic',true,null, 55, 27),
('exercise','build','health',
  '{"ar":"ممارسة الرياضة","en":"Exercise","fr":"Faire du sport"}',
  '{"ar":"حرّك جسمك كل يوم","en":"Move your body daily.","fr":"Bougez chaque jour."}',
  '🏃','generic',false,null, 92, 28),
('drink_water','build','health',
  '{"ar":"شرب الماء بانتظام","en":"Drink water","fr":"Boire de l''eau"}',
  '{"ar":"رطّب جسمك على مدار اليوم","en":"Stay hydrated.","fr":"Restez hydraté."}',
  '💧','generic',false,null, 80, 29),
('read_books','build','productivity',
  '{"ar":"القراءة اليومية","en":"Daily reading","fr":"Lecture quotidienne"}',
  '{"ar":"صفحات كل يوم تبني عقلك","en":"A few pages every day.","fr":"Quelques pages chaque jour."}',
  '📚','generic',false,null, 78, 30),
('sleep_early','build','health',
  '{"ar":"النوم مبكراً","en":"Sleep early","fr":"Dormir tôt"}',
  '{"ar":"نوم مبكر = استيقاظ للفجر بنشاط","en":"Early to bed, up for Fajr.","fr":"Au lit tôt."}',
  '🌃','generic',false,null, 72, 31),
('gratitude','build','mind',
  '{"ar":"الحمد والشكر","en":"Praise & gratitude","fr":"Louange et gratitude"}',
  '{"ar":"احمد الله على نِعَمه واشكره كل يوم","en":"Praise Allah for His blessings and thank Him daily.","fr":"Louez Dieu pour Ses bienfaits et remerciez-Le chaque jour."}',
  '🤍','generic',true,null, 68, 32),
('learn_skill','build','productivity',
  '{"ar":"تعلّم مهارة جديدة","en":"Learn a new skill","fr":"Apprendre une compétence"}',
  '{"ar":"تقدّم بسيط كل يوم","en":"A little progress daily.","fr":"Un peu de progrès chaque jour."}',
  '🧠','generic',false,null, 64, 33),
('wake_fajr','build','worship',
  '{"ar":"الاستيقاظ للفجر","en":"Wake up for Fajr","fr":"Se lever pour Fajr"}',
  '{"ar":"بركة يومك تبدأ من الفجر","en":"Begin your day with Fajr.","fr":"Commencez par Fajr."}',
  '🌅','generic',true,null, 88, 34);

-- New habits (2026-06-28): 3 build + 3 break, popular among Arabs/Muslims.
insert into public.habit_catalog (key, track, category, title, description, icon, default_template_key, is_islamic, islamweb_ref, popularity, sort_order) values
('salawat','build','worship',
  '{"ar":"الصلاة على النبي","en":"Salawat on the Prophet","fr":"Salawat sur le Prophète"}',
  '{"ar":"أكثِر من الصلاة على النبي صلى الله عليه وسلم، فهي نورٌ لقلبك وسببٌ لرفعة درجاتك، وأكثِر منها يوم الجمعة.","en":"Send abundant blessings upon the Prophet, peace be upon him. It brings light to your heart and raises your rank, especially on Fridays.","fr":"Multipliez les prières sur le Prophète, paix sur lui. Elles illuminent le cœur et élèvent les rangs, surtout le vendredi."}',
  '🌹','generic',true,null, 50, 50),
('honor_parents','build','social',
  '{"ar":"بر الوالدين","en":"Honoring your parents","fr":"Honorer ses parents"}',
  '{"ar":"أحسِن إلى والديك كل يوم بكلمة طيبة أو خدمة أو دعاء، فرضاهما من رضا الله، وبرّهما باب من أبواب الجنة.","en":"Be good to your parents every day with a kind word, a service, or a prayer. Their pleasure is from God''s pleasure, and honoring them is a gate to Paradise.","fr":"Soyez bon envers vos parents chaque jour par une parole douce, un service ou une prière. Leur satisfaction relève de celle de Dieu, et les honorer est une porte du Paradis."}',
  '👵','generic',true,null, 50, 51),
('dua','build','worship',
  '{"ar":"الدعاء اليومي","en":"Daily supplication","fr":"Invocation quotidienne"}',
  '{"ar":"اجعل لك نصيباً ثابتاً من الدعاء كل يوم، وارفع حاجاتك إلى الله بقلب موقن بالإجابة، فالدعاء مفتاح كل خير.","en":"Set aside a steady portion of supplication each day, raising your needs to God with a heart certain of an answer. Supplication is the key to every good.","fr":"Réservez chaque jour un moment d''invocation, en présentant vos besoins à Dieu avec un cœur convaincu de la réponse. L''invocation est la clé de tout bien."}',
  '🤍','generic',true,null, 50, 52),
('late_nights','break','health',
  '{"ar":"السهر المتأخر","en":"Staying up late","fr":"Veiller tard"}',
  '{"ar":"تخلّص من عادة السهر المتأخر الذي يسرق نومك وصلاة فجرك ونشاط نهارك، ونظّم وقت نومك.","en":"Break the habit of staying up late, which steals your sleep, your Fajr prayer, and your daytime energy. Regulate your bedtime.","fr":"Rompez avec l''habitude de veiller tard, qui vous prive de sommeil, de la prière de Fajr et de votre énergie. Régulez l''heure du coucher."}',
  '🌙','hrt_8week',false,null, 50, 53),
('binge_watching','break','productivity',
  '{"ar":"الإفراط في المشاهدة","en":"Binge-watching","fr":"Visionnage excessif"}',
  '{"ar":"قلّل ساعات مشاهدة المسلسلات والمقاطع القصيرة المتواصلة التي تسرق وقتك وتركيزك، واسترجع ساعاتك لما ينفعك.","en":"Cut back on hours of nonstop series and short clips that steal your time and focus, and reclaim your hours for what benefits you.","fr":"Réduisez les heures de séries et de clips courts ininterrompus qui volent votre temps et votre concentration, et récupérez vos heures pour ce qui est utile."}',
  '📺','hrt_8week',false,null, 50, 54),
('anger','break','mind',
  '{"ar":"الغضب وسرعة الانفعال","en":"Anger & quick temper","fr":"Colère et emportement"}',
  '{"ar":"تعلّم ضبط غضبك وكظم غيظك في المواقف الصعبة، فالقوي من يملك نفسه عند الغضب، واحفظ علاقاتك وصحتك.","en":"Learn to control your anger and restrain it in difficult moments. The strong one is who masters himself when angry, protecting your relationships and health.","fr":"Apprenez à maîtriser votre colère et à la contenir dans les moments difficiles. Le fort est celui qui se domine quand il est en colère, préservant ses relations et sa santé."}',
  '😤','hrt_8week',true,null, 50, 55),
-- New religious habits (2026-07-17): Surah Al-Kahf (weekly) + porn-break.
('surah_kahf','build','worship',
  '{"ar":"قراءة سورة الكهف","en":"Reading Surah Al-Kahf","fr":"Lecture de sourate Al-Kahf"}',
  '{"ar":"اقرأ سورة الكهف كل جمعة، فمن قرأها أضاء له من النور ما بين الجمعتين. اجعلها موعداً ثابتاً بعد صلاة الجمعة.","en":"Read Surah Al-Kahf every Friday; whoever reads it is granted light between the two Fridays. Make it a fixed appointment after Jumu''ah.","fr":"Lisez la sourate Al-Kahf chaque vendredi; celui qui la lit reçoit une lumière entre les deux vendredis. Fixez ce rendez-vous après la prière du vendredi."}',
  '📖','generic',true,'https://www.islamweb.net/ar/fatwa/21395/', 50, 56),
('break_porn','break','mind',
  '{"ar":"كسر إدمان الإباحية","en":"Break porn addiction","fr":"Briser l''addiction au porno"}',
  '{"ar":"طريق التعافي يبدأ بصدق التوبة وقطع الطريق على المحرَّم. فعّل حاجب المحتوى، واملأ فراغك بالخير، واستعن بالله ثم بمن تثق به.","en":"Recovery starts with sincere repentance and cutting off access. Turn on the content shield, fill your time with good, and lean on God then a trusted companion.","fr":"La guérison commence par un repentir sincère et la coupure de l''accès. Activez le filtre de contenu, occupez votre temps par le bien, et appuyez-vous sur Dieu puis sur une personne de confiance."}',
  '🛡️','hrt_8week',true,'https://www.islamweb.net/ar/fatwa/125402/', 50, 57),
('listening_wird','build','worship',
  '{"ar":"ورد الاستماع للقرآن","en":"Quran listening wird","fr":"Wird d''écoute du Coran"}',
  '{"ar":"اجعل لك وِرداً يومياً تستمع فيه إلى القرآن بصوت قارئك المفضّل، فللاستماع للقرآن سكينةٌ للقلب ورحمة. اختر السورة وعدد ما تسمع.","en":"Set a daily wird of listening to the Quran in your favourite reciter''s voice; listening brings calm and mercy to the heart.","fr":"Fixez un wird quotidien d''écoute du Coran par votre récitateur préféré; l''écoute apporte sérénité et miséricorde au cœur."}',
  '🎧','generic',true,'https://www.islamweb.net/ar/fatwa/13782/', 50, 58),
('hadith_wird','build','worship',
  '{"ar":"ورد الاستماع للسنة","en":"Sunnah listening wird","fr":"Wird d''écoute de la Sunna"}',
  '{"ar":"استمع يومياً إلى أحاديث النبي صلى الله عليه وسلم من صحيح البخاري ومسلم ورياض الصالحين، بثاً مباشراً. يُسجَّل وردك تلقائياً بعد الاستماع.","en":"Listen daily to the Prophet''s hadith from Sahih al-Bukhari, Muslim and Riyad as-Salihin via live radio. Auto-logged after listening.","fr":"Écoutez chaque jour les hadiths du Prophète depuis Sahih al-Bukhari, Muslim et Riyad as-Salihin en direct."}',
  '📻','generic',true,'https://www.islamweb.net/ar/fatwa/10054/', 50, 59)
on conflict (key) do nothing;
