-- ============================================================
-- seed.sql — reference data: habit_catalog + badge_definitions
-- Trilingual (ar/en/fr). Run via `supabase db reset`.
-- ============================================================

-- ---------- BADGE DEFINITIONS (streak shields + more) ----------
insert into public.badge_definitions (key, tier, category, title, description, icon, criteria_type, threshold, sort_order) values
('first_log','bronze','milestone',
  '{"ar":"أول خطوة","en":"First Step","fr":"Premier pas"}',
  '{"ar":"سجّلت أول يوم — البداية أصعب خطوة 🌱","en":"You logged your first day.","fr":"Vous avez enregistré votre premier jour."}',
  '🌱','first_log',1,1),
('streak_3','bronze','streak',
  '{"ar":"٣ أيام متتالية","en":"3-Day Streak","fr":"Série de 3 jours"}',
  '{"ar":"العادة بدأت تتشكّل — استمر 💪","en":"The habit is forming.","fr":"L''habitude se forme."}',
  '💪','streak_clean_days',3,2),
('streak_7','bronze','streak',
  '{"ar":"أسبوع كامل","en":"One Week","fr":"Une semaine"}',
  '{"ar":"أسبوع بلا تعثّر — الدماغ يتغيّر ⭐","en":"A full clean week.","fr":"Une semaine complète."}',
  '⭐','streak_clean_days',7,3),
('streak_14','bronze','streak',
  '{"ar":"أسبوعان","en":"Two Weeks","fr":"Deux semaines"}',
  '{"ar":"إنجاز حقيقي — الدائرة العصبية تتبدّل","en":"Two weeks strong.","fr":"Deux semaines."}',
  '🔥','streak_clean_days',14,4),
('streak_30_silver','silver','streak',
  '{"ar":"درع فضي — ٣٠ يوم","en":"Silver Shield — 30 Days","fr":"Bouclier argent — 30 jours"}',
  '{"ar":"شهر كامل! إنجاز يستحق الفخر 🥈","en":"A full month — proud of you!","fr":"Un mois entier !"}',
  '🥈','streak_clean_days',30,5),
('streak_60_gold','gold','streak',
  '{"ar":"درع ذهبي — ٦٠ يوم","en":"Gold Shield — 60 Days","fr":"Bouclier or — 60 jours"}',
  '{"ar":"شهران متتاليان — أنت في مرحلة متقدمة 🥇","en":"Two months in a row!","fr":"Deux mois d''affilée !"}',
  '🥇','streak_clean_days',60,6),
('streak_90_diamond','diamond','streak',
  '{"ar":"درع ماسي — ٩٠ يوم","en":"Diamond Shield — 90 Days","fr":"Bouclier diamant — 90 jours"}',
  '{"ar":"٩٠ يوم! العادة الجديدة أصبحت جزءاً منك 💎","en":"90 days — a new you!","fr":"90 jours — un nouveau vous !"}',
  '💎','streak_clean_days',90,7),
('streak_180_diamond','diamond','streak',
  '{"ar":"ماسة الصبر — ١٨٠ يوم","en":"Patience Diamond — 180 Days","fr":"Diamant patience — 180 jours"}',
  '{"ar":"نصف عام من الثبات — مَثَل يُحتذى","en":"Half a year of consistency.","fr":"Six mois de constance."}',
  '💎','streak_clean_days',180,8),
('comeback','special','recovery',
  '{"ar":"العودة أقوى","en":"Stronger Comeback","fr":"Retour plus fort"}',
  '{"ar":"تعثّرت ورجعت — ده عين النجاح 🤍","en":"You stumbled and came back.","fr":"Vous êtes revenu plus fort."}',
  '🤍','comeback_after_relapse',1,9),
('logged_30','silver','consistency',
  '{"ar":"مواظب — ٣٠ تسجيلة","en":"Consistent — 30 Logs","fr":"Assidu — 30 journaux"}',
  '{"ar":"٣٠ يوم من المتابعة المنتظمة","en":"30 days of tracking.","fr":"30 jours de suivi."}',
  '📈','days_logged',30,10);

-- ---------- HABIT CATALOG ----------
-- BREAK track
insert into public.habit_catalog (key, track, category, title, description, icon, default_template_key, is_islamic, islamweb_ref, popularity, sort_order) values
('quit_smoking','break','health',
  '{"ar":"الإقلاع عن التدخين","en":"Quit smoking","fr":"Arrêter de fumer"}',
  '{"ar":"تحرّر من السجائر خطوة بخطوة","en":"Break free from cigarettes.","fr":"Libérez-vous de la cigarette."}',
  '🚭','hrt_8week',false,'https://www.islamweb.net/ar/fatwa/4257/', 100, 1),
('quit_vaping','break','health',
  '{"ar":"ترك الفيب","en":"Quit vaping","fr":"Arrêter la vape"}',
  '{"ar":"توقّف عن التدخين الإلكتروني","en":"Stop e-cigarettes.","fr":"Arrêtez l''e-cigarette."}',
  '💨','hrt_8week',false,null, 70, 2),
('nail_biting','break','mind',
  '{"ar":"قضم الأظافر","en":"Nail biting","fr":"Rongement des ongles"}',
  '{"ar":"عادة عصبية شائعة — نتعامل معها بوعي","en":"A common nervous habit.","fr":"Une habitude nerveuse courante."}',
  '💅','hrt_8week',false,null, 80, 3),
('hair_pulling','break','mind',
  '{"ar":"نتف الشعر (هوس النتف)","en":"Hair pulling (Trichotillomania)","fr":"Arrachage de cheveux"}',
  '{"ar":"متابعة بمنهج HRT العلمي","en":"Tracked with the evidence-based HRT method.","fr":"Suivi avec la méthode HRT."}',
  '💇','hrt_8week',false,null, 60, 4),
('skin_picking','break','mind',
  '{"ar":"نتش الجلد","en":"Skin picking","fr":"Grattage de la peau"}',
  '{"ar":"عادة جلدية متكررة — نخفّفها بالتدريب","en":"A repetitive skin habit.","fr":"Une habitude cutanée répétitive."}',
  '🤚','hrt_8week',false,null, 40, 5),
('phone_addiction','break','productivity',
  '{"ar":"إدمان الموبايل","en":"Phone addiction","fr":"Addiction au téléphone"}',
  '{"ar":"قلّل التصفّح اللاواعي واسترجع وقتك","en":"Reclaim your time from doomscrolling.","fr":"Reprenez votre temps."}',
  '📱','generic',false,null, 95, 6),
('excessive_gaming','break','productivity',
  '{"ar":"الإفراط في الألعاب","en":"Excessive gaming","fr":"Jeux excessifs"}',
  '{"ar":"توازن أفضل مع الألعاب","en":"Find a healthier balance.","fr":"Trouvez l''équilibre."}',
  '🎮','generic',false,null, 55, 7),
('procrastination','break','productivity',
  '{"ar":"التسويف والمماطلة","en":"Procrastination","fr":"Procrastination"}',
  '{"ar":"ابدأ بدل ما تأجّل","en":"Start instead of postponing.","fr":"Commencez au lieu de reporter."}',
  '⏳','generic',false,null, 85, 8),
('junk_food','break','health',
  '{"ar":"الأكل غير الصحي","en":"Junk food","fr":"Malbouffe"}',
  '{"ar":"قلّل السكر والوجبات السريعة","en":"Cut sugar and fast food.","fr":"Réduisez le sucre."}',
  '🍔','generic',false,null, 75, 9),
('oversleeping','break','health',
  '{"ar":"كثرة النوم","en":"Oversleeping","fr":"Trop dormir"}',
  '{"ar":"نظّم نومك واستيقظ بنشاط","en":"Regulate your sleep.","fr":"Régulez votre sommeil."}',
  '😴','generic',false,null, 50, 10),
('gossip','break','social',
  '{"ar":"الغيبة والنميمة","en":"Gossip & backbiting","fr":"Médisance"}',
  '{"ar":"احفظ لسانك — خير لك في دينك ودنياك","en":"Guard your tongue.","fr":"Préservez votre langue."}',
  '🤐','generic',true,'https://www.islamweb.net/ar/fatwa/1531/', 45, 11),
('bad_language','break','social',
  '{"ar":"الألفاظ السيّئة","en":"Bad language","fr":"Langage grossier"}',
  '{"ar":"كلام طيّب وأخلاق أحسن","en":"Cleaner, kinder speech.","fr":"Un langage plus doux."}',
  '🗯️','generic',true,null, 35, 12),
('impulse_buying','break','productivity',
  '{"ar":"الشراء الاندفاعي","en":"Impulse buying","fr":"Achats impulsifs"}',
  '{"ar":"قرارات إنفاق أوعى","en":"Smarter spending decisions.","fr":"Des dépenses plus réfléchies."}',
  '🛍️','generic',false,null, 40, 13),
('caffeine_excess','break','health',
  '{"ar":"الإفراط في الكافيين","en":"Too much caffeine","fr":"Excès de caféine"}',
  '{"ar":"قلّل القهوة ومشروبات الطاقة","en":"Cut back on coffee/energy drinks.","fr":"Réduisez la caféine."}',
  '☕','generic',false,null, 38, 14);

-- BUILD track
insert into public.habit_catalog (key, track, category, title, description, icon, default_template_key, is_islamic, islamweb_ref, popularity, sort_order) values
('pray_on_time','build','worship',
  '{"ar":"المحافظة على الصلاة في وقتها","en":"Pray on time","fr":"Prier à l''heure"}',
  '{"ar":"عماد الدين — حافظ على صلواتك الخمس","en":"Keep the five daily prayers on time.","fr":"Les cinq prières à l''heure."}',
  '🕌','generic',true,'https://www.islamweb.net/ar/fatwa/13619/', 100, 20),
('daily_quran','build','worship',
  '{"ar":"وِرد القرآن اليومي","en":"Daily Qur''an","fr":"Coran quotidien"}',
  '{"ar":"اجعل لك وِرداً ثابتاً من كتاب الله","en":"A steady daily portion of Qur''an.","fr":"Une portion quotidienne du Coran."}',
  '📖','generic',true,null, 95, 21),
('adhkar','build','worship',
  '{"ar":"أذكار الصباح والمساء","en":"Morning & evening adhkar","fr":"Adhkar matin et soir"}',
  '{"ar":"حصّن يومك بالذكر","en":"Fortify your day with remembrance.","fr":"Protégez votre journée."}',
  '📿','generic',true,null, 90, 22),
('voluntary_fasting','build','worship',
  '{"ar":"صيام النفل","en":"Voluntary fasting","fr":"Jeûne surérogatoire"}',
  '{"ar":"الإثنين والخميس والأيام البيض","en":"Mondays, Thursdays, white days.","fr":"Lundi, jeudi, jours blancs."}',
  '🌙','generic',true,'https://www.islamweb.net/ar/fatwa/50964/', 70, 23),
('qiyam','build','worship',
  '{"ar":"قيام الليل","en":"Night prayer (Qiyam)","fr":"Prière de nuit"}',
  '{"ar":"شرف المؤمن قيامه بالليل","en":"The honor of the believer.","fr":"L''honneur du croyant."}',
  '🌌','generic',true,null, 65, 24),
('keeping_ties','build','social',
  '{"ar":"صلة الرحم","en":"Keeping family ties","fr":"Liens familiaux"}',
  '{"ar":"تواصل مع أهلك وقرابتك","en":"Stay connected with your kin.","fr":"Restez en lien avec vos proches."}',
  '🤝','generic',true,null, 60, 25),
('daily_charity','build','worship',
  '{"ar":"صدقة يومية","en":"Daily charity","fr":"Aumône quotidienne"}',
  '{"ar":"ولو بالقليل — الصدقة تطفئ الخطيئة","en":"Even a little, every day.","fr":"Même peu, chaque jour."}',
  '💝','generic',true,null, 58, 26),
('istighfar','build','worship',
  '{"ar":"الاستغفار اليومي","en":"Daily istighfar","fr":"Istighfar quotidien"}',
  '{"ar":"عوّد لسانك على الاستغفار","en":"Keep your tongue moist with istighfar.","fr":"Habituez votre langue à l''istighfar."}',
  '🤲','generic',true,null, 55, 27),
('exercise','build','health',
  '{"ar":"ممارسة الرياضة","en":"Exercise","fr":"Faire du sport"}',
  '{"ar":"حرّك جسمك كل يوم","en":"Move your body daily.","fr":"Bougez chaque jour."}',
  '🏃','generic',false,null, 92, 28),
('drink_water','build','health',
  '{"ar":"شرب الماء بانتظام","en":"Drink water","fr":"Boire de l''eau"}',
  '{"ar":"رطّب جسمك على مدار اليوم","en":"Stay hydrated.","fr":"Restez hydraté."}',
  '💧','generic',false,null, 80, 29),
('read_books','build','productivity',
  '{"ar":"القراءة اليومية","en":"Daily reading","fr":"Lecture quotidienne"}',
  '{"ar":"صفحات كل يوم تبني عقلك","en":"A few pages every day.","fr":"Quelques pages chaque jour."}',
  '📚','generic',false,null, 78, 30),
('sleep_early','build','health',
  '{"ar":"النوم مبكراً","en":"Sleep early","fr":"Dormir tôt"}',
  '{"ar":"نوم مبكر = استيقاظ للفجر بنشاط","en":"Early to bed, up for Fajr.","fr":"Au lit tôt."}',
  '🌃','generic',false,null, 72, 31),
('gratitude','build','mind',
  '{"ar":"الامتنان اليومي","en":"Gratitude journal","fr":"Journal de gratitude"}',
  '{"ar":"اكتب نِعَمك كل يوم","en":"Note your blessings daily.","fr":"Notez vos bienfaits."}',
  '🤍','generic',true,null, 68, 32),
('learn_skill','build','productivity',
  '{"ar":"تعلّم مهارة جديدة","en":"Learn a new skill","fr":"Apprendre une compétence"}',
  '{"ar":"تقدّم بسيط كل يوم","en":"A little progress daily.","fr":"Un peu de progrès chaque jour."}',
  '🧠','generic',false,null, 64, 33),
('wake_fajr','build','worship',
  '{"ar":"الاستيقاظ للفجر","en":"Wake up for Fajr","fr":"Se lever pour Fajr"}',
  '{"ar":"بركة يومك تبدأ من الفجر","en":"Begin your day with Fajr.","fr":"Commencez par Fajr."}',
  '🌅','generic',true,null, 88, 34);
