// Trilingual country list (ar/en/fr) for the onboarding country picker.
// name(locale) returns the country name in the app's selected language; search
// also matches on the localized name. Arab/MENA countries are listed first
// (primary audience), then the rest alphabetically by English name.

class Country {
  final String code; // ISO 3166-1 alpha-2
  final String ar;
  final String en;
  final String fr;
  const Country(this.code, this.ar, this.en, this.fr);

  String name(String locale) =>
      locale == 'en' ? en : (locale == 'fr' ? fr : ar);
}

const List<Country> kCountries = [
  // ---- Arab / MENA (listed first) ----
  Country('SA', 'السعودية', 'Saudi Arabia', 'Arabie saoudite'),
  Country('EG', 'مصر', 'Egypt', 'Égypte'),
  Country('AE', 'الإمارات العربية المتحدة', 'United Arab Emirates', 'Émirats arabes unis'),
  Country('QA', 'قطر', 'Qatar', 'Qatar'),
  Country('KW', 'الكويت', 'Kuwait', 'Koweït'),
  Country('BH', 'البحرين', 'Bahrain', 'Bahreïn'),
  Country('OM', 'عُمان', 'Oman', 'Oman'),
  Country('YE', 'اليمن', 'Yemen', 'Yémen'),
  Country('JO', 'الأردن', 'Jordan', 'Jordanie'),
  Country('PS', 'فلسطين', 'Palestine', 'Palestine'),
  Country('LB', 'لبنان', 'Lebanon', 'Liban'),
  Country('SY', 'سوريا', 'Syria', 'Syrie'),
  Country('IQ', 'العراق', 'Iraq', 'Irak'),
  Country('SD', 'السودان', 'Sudan', 'Soudan'),
  Country('LY', 'ليبيا', 'Libya', 'Libye'),
  Country('TN', 'تونس', 'Tunisia', 'Tunisie'),
  Country('DZ', 'الجزائر', 'Algeria', 'Algérie'),
  Country('MA', 'المغرب', 'Morocco', 'Maroc'),
  Country('MR', 'موريتانيا', 'Mauritania', 'Mauritanie'),
  Country('SO', 'الصومال', 'Somalia', 'Somalie'),
  Country('DJ', 'جيبوتي', 'Djibouti', 'Djibouti'),
  Country('KM', 'جزر القمر', 'Comoros', 'Comores'),

  // ---- Rest of the world (alphabetical by English) ----
  Country('AF', 'أفغانستان', 'Afghanistan', 'Afghanistan'),
  Country('AL', 'ألبانيا', 'Albania', 'Albanie'),
  Country('AD', 'أندورا', 'Andorra', 'Andorre'),
  Country('AO', 'أنغولا', 'Angola', 'Angola'),
  Country('AG', 'أنتيغوا وباربودا', 'Antigua and Barbuda', 'Antigua-et-Barbuda'),
  Country('AR', 'الأرجنتين', 'Argentina', 'Argentine'),
  Country('AM', 'أرمينيا', 'Armenia', 'Arménie'),
  Country('AU', 'أستراليا', 'Australia', 'Australie'),
  Country('AT', 'النمسا', 'Austria', 'Autriche'),
  Country('AZ', 'أذربيجان', 'Azerbaijan', 'Azerbaïdjan'),
  Country('BS', 'الباهاما', 'Bahamas', 'Bahamas'),
  Country('BD', 'بنغلاديش', 'Bangladesh', 'Bangladesh'),
  Country('BB', 'باربادوس', 'Barbados', 'Barbade'),
  Country('BY', 'بيلاروسيا', 'Belarus', 'Biélorussie'),
  Country('BE', 'بلجيكا', 'Belgium', 'Belgique'),
  Country('BZ', 'بليز', 'Belize', 'Belize'),
  Country('BJ', 'بنين', 'Benin', 'Bénin'),
  Country('BT', 'بوتان', 'Bhutan', 'Bhoutan'),
  Country('BO', 'بوليفيا', 'Bolivia', 'Bolivie'),
  Country('BA', 'البوسنة والهرسك', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine'),
  Country('BW', 'بوتسوانا', 'Botswana', 'Botswana'),
  Country('BR', 'البرازيل', 'Brazil', 'Brésil'),
  Country('BN', 'بروناي', 'Brunei', 'Brunei'),
  Country('BG', 'بلغاريا', 'Bulgaria', 'Bulgarie'),
  Country('BF', 'بوركينا فاسو', 'Burkina Faso', 'Burkina Faso'),
  Country('BI', 'بوروندي', 'Burundi', 'Burundi'),
  Country('CV', 'الرأس الأخضر', 'Cabo Verde', 'Cap-Vert'),
  Country('KH', 'كمبوديا', 'Cambodia', 'Cambodge'),
  Country('CM', 'الكاميرون', 'Cameroon', 'Cameroun'),
  Country('CA', 'كندا', 'Canada', 'Canada'),
  Country('CF', 'جمهورية أفريقيا الوسطى', 'Central African Republic', 'République centrafricaine'),
  Country('TD', 'تشاد', 'Chad', 'Tchad'),
  Country('CL', 'تشيلي', 'Chile', 'Chili'),
  Country('CN', 'الصين', 'China', 'Chine'),
  Country('CO', 'كولومبيا', 'Colombia', 'Colombie'),
  Country('CG', 'الكونغو', 'Congo', 'Congo'),
  Country('CD', 'جمهورية الكونغو الديمقراطية', 'DR Congo', 'RD Congo'),
  Country('CR', 'كوستاريكا', 'Costa Rica', 'Costa Rica'),
  Country('CI', 'ساحل العاج', 'Côte d\'Ivoire', 'Côte d\'Ivoire'),
  Country('HR', 'كرواتيا', 'Croatia', 'Croatie'),
  Country('CU', 'كوبا', 'Cuba', 'Cuba'),
  Country('CY', 'قبرص', 'Cyprus', 'Chypre'),
  Country('CZ', 'التشيك', 'Czechia', 'Tchéquie'),
  Country('DK', 'الدنمارك', 'Denmark', 'Danemark'),
  Country('DM', 'دومينيكا', 'Dominica', 'Dominique'),
  Country('DO', 'جمهورية الدومينيكان', 'Dominican Republic', 'République dominicaine'),
  Country('EC', 'الإكوادور', 'Ecuador', 'Équateur'),
  Country('SV', 'السلفادور', 'El Salvador', 'Salvador'),
  Country('GQ', 'غينيا الاستوائية', 'Equatorial Guinea', 'Guinée équatoriale'),
  Country('ER', 'إريتريا', 'Eritrea', 'Érythrée'),
  Country('EE', 'إستونيا', 'Estonia', 'Estonie'),
  Country('SZ', 'إسواتيني', 'Eswatini', 'Eswatini'),
  Country('ET', 'إثيوبيا', 'Ethiopia', 'Éthiopie'),
  Country('FJ', 'فيجي', 'Fiji', 'Fidji'),
  Country('FI', 'فنلندا', 'Finland', 'Finlande'),
  Country('FR', 'فرنسا', 'France', 'France'),
  Country('GA', 'الغابون', 'Gabon', 'Gabon'),
  Country('GM', 'غامبيا', 'Gambia', 'Gambie'),
  Country('GE', 'جورجيا', 'Georgia', 'Géorgie'),
  Country('DE', 'ألمانيا', 'Germany', 'Allemagne'),
  Country('GH', 'غانا', 'Ghana', 'Ghana'),
  Country('GR', 'اليونان', 'Greece', 'Grèce'),
  Country('GD', 'غرينادا', 'Grenada', 'Grenade'),
  Country('GT', 'غواتيمالا', 'Guatemala', 'Guatemala'),
  Country('GN', 'غينيا', 'Guinea', 'Guinée'),
  Country('GW', 'غينيا بيساو', 'Guinea-Bissau', 'Guinée-Bissau'),
  Country('GY', 'غيانا', 'Guyana', 'Guyana'),
  Country('HT', 'هايتي', 'Haiti', 'Haïti'),
  Country('HN', 'هندوراس', 'Honduras', 'Honduras'),
  Country('HU', 'المجر', 'Hungary', 'Hongrie'),
  Country('IS', 'آيسلندا', 'Iceland', 'Islande'),
  Country('IN', 'الهند', 'India', 'Inde'),
  Country('ID', 'إندونيسيا', 'Indonesia', 'Indonésie'),
  Country('IR', 'إيران', 'Iran', 'Iran'),
  Country('IE', 'أيرلندا', 'Ireland', 'Irlande'),
  Country('IT', 'إيطاليا', 'Italy', 'Italie'),
  Country('JM', 'جامايكا', 'Jamaica', 'Jamaïque'),
  Country('JP', 'اليابان', 'Japan', 'Japon'),
  Country('KZ', 'كازاخستان', 'Kazakhstan', 'Kazakhstan'),
  Country('KE', 'كينيا', 'Kenya', 'Kenya'),
  Country('KI', 'كيريباتي', 'Kiribati', 'Kiribati'),
  Country('KP', 'كوريا الشمالية', 'North Korea', 'Corée du Nord'),
  Country('KR', 'كوريا الجنوبية', 'South Korea', 'Corée du Sud'),
  Country('KG', 'قيرغيزستان', 'Kyrgyzstan', 'Kirghizistan'),
  Country('LA', 'لاوس', 'Laos', 'Laos'),
  Country('LV', 'لاتفيا', 'Latvia', 'Lettonie'),
  Country('LS', 'ليسوتو', 'Lesotho', 'Lesotho'),
  Country('LR', 'ليبيريا', 'Liberia', 'Liberia'),
  Country('LI', 'ليختنشتاين', 'Liechtenstein', 'Liechtenstein'),
  Country('LT', 'ليتوانيا', 'Lithuania', 'Lituanie'),
  Country('LU', 'لوكسمبورغ', 'Luxembourg', 'Luxembourg'),
  Country('MG', 'مدغشقر', 'Madagascar', 'Madagascar'),
  Country('MW', 'مالاوي', 'Malawi', 'Malawi'),
  Country('MY', 'ماليزيا', 'Malaysia', 'Malaisie'),
  Country('MV', 'المالديف', 'Maldives', 'Maldives'),
  Country('ML', 'مالي', 'Mali', 'Mali'),
  Country('MT', 'مالطا', 'Malta', 'Malte'),
  Country('MH', 'جزر مارشال', 'Marshall Islands', 'Îles Marshall'),
  Country('MU', 'موريشيوس', 'Mauritius', 'Maurice'),
  Country('MX', 'المكسيك', 'Mexico', 'Mexique'),
  Country('FM', 'ميكرونيزيا', 'Micronesia', 'Micronésie'),
  Country('MD', 'مولدوفا', 'Moldova', 'Moldavie'),
  Country('MC', 'موناكو', 'Monaco', 'Monaco'),
  Country('MN', 'منغوليا', 'Mongolia', 'Mongolie'),
  Country('ME', 'الجبل الأسود', 'Montenegro', 'Monténégro'),
  Country('MZ', 'موزمبيق', 'Mozambique', 'Mozambique'),
  Country('MM', 'ميانمار', 'Myanmar', 'Myanmar'),
  Country('NA', 'ناميبيا', 'Namibia', 'Namibie'),
  Country('NR', 'ناورو', 'Nauru', 'Nauru'),
  Country('NP', 'نيبال', 'Nepal', 'Népal'),
  Country('NL', 'هولندا', 'Netherlands', 'Pays-Bas'),
  Country('NZ', 'نيوزيلندا', 'New Zealand', 'Nouvelle-Zélande'),
  Country('NI', 'نيكاراغوا', 'Nicaragua', 'Nicaragua'),
  Country('NE', 'النيجر', 'Niger', 'Niger'),
  Country('NG', 'نيجيريا', 'Nigeria', 'Nigéria'),
  Country('MK', 'مقدونيا الشمالية', 'North Macedonia', 'Macédoine du Nord'),
  Country('NO', 'النرويج', 'Norway', 'Norvège'),
  Country('PK', 'باكستان', 'Pakistan', 'Pakistan'),
  Country('PW', 'بالاو', 'Palau', 'Palaos'),
  Country('PA', 'بنما', 'Panama', 'Panama'),
  Country('PG', 'بابوا غينيا الجديدة', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée'),
  Country('PY', 'باراغواي', 'Paraguay', 'Paraguay'),
  Country('PE', 'بيرو', 'Peru', 'Pérou'),
  Country('PH', 'الفلبين', 'Philippines', 'Philippines'),
  Country('PL', 'بولندا', 'Poland', 'Pologne'),
  Country('PT', 'البرتغال', 'Portugal', 'Portugal'),
  Country('RO', 'رومانيا', 'Romania', 'Roumanie'),
  Country('RU', 'روسيا', 'Russia', 'Russie'),
  Country('RW', 'رواندا', 'Rwanda', 'Rwanda'),
  Country('KN', 'سانت كيتس ونيفيس', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis'),
  Country('LC', 'سانت لوسيا', 'Saint Lucia', 'Sainte-Lucie'),
  Country('VC', 'سانت فينسنت والغرينادين', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les-Grenadines'),
  Country('WS', 'ساموا', 'Samoa', 'Samoa'),
  Country('SM', 'سان مارينو', 'San Marino', 'Saint-Marin'),
  Country('ST', 'ساو تومي وبرينسيب', 'São Tomé and Príncipe', 'Sao Tomé-et-Principe'),
  Country('SN', 'السنغال', 'Senegal', 'Sénégal'),
  Country('RS', 'صربيا', 'Serbia', 'Serbie'),
  Country('SC', 'سيشل', 'Seychelles', 'Seychelles'),
  Country('SL', 'سيراليون', 'Sierra Leone', 'Sierra Leone'),
  Country('SG', 'سنغافورة', 'Singapore', 'Singapour'),
  Country('SK', 'سلوفاكيا', 'Slovakia', 'Slovaquie'),
  Country('SI', 'سلوفينيا', 'Slovenia', 'Slovénie'),
  Country('SB', 'جزر سليمان', 'Solomon Islands', 'Îles Salomon'),
  Country('ZA', 'جنوب أفريقيا', 'South Africa', 'Afrique du Sud'),
  Country('SS', 'جنوب السودان', 'South Sudan', 'Soudan du Sud'),
  Country('ES', 'إسبانيا', 'Spain', 'Espagne'),
  Country('LK', 'سريلانكا', 'Sri Lanka', 'Sri Lanka'),
  Country('SR', 'سورينام', 'Suriname', 'Suriname'),
  Country('SE', 'السويد', 'Sweden', 'Suède'),
  Country('CH', 'سويسرا', 'Switzerland', 'Suisse'),
  Country('TJ', 'طاجيكستان', 'Tajikistan', 'Tadjikistan'),
  Country('TZ', 'تنزانيا', 'Tanzania', 'Tanzanie'),
  Country('TH', 'تايلاند', 'Thailand', 'Thaïlande'),
  Country('TL', 'تيمور الشرقية', 'Timor-Leste', 'Timor oriental'),
  Country('TG', 'توغو', 'Togo', 'Togo'),
  Country('TO', 'تونغا', 'Tonga', 'Tonga'),
  Country('TT', 'ترينيداد وتوباغو', 'Trinidad and Tobago', 'Trinité-et-Tobago'),
  Country('TR', 'تركيا', 'Turkey', 'Turquie'),
  Country('TM', 'تركمانستان', 'Turkmenistan', 'Turkménistan'),
  Country('TV', 'توفالو', 'Tuvalu', 'Tuvalu'),
  Country('UG', 'أوغندا', 'Uganda', 'Ouganda'),
  Country('UA', 'أوكرانيا', 'Ukraine', 'Ukraine'),
  Country('GB', 'المملكة المتحدة', 'United Kingdom', 'Royaume-Uni'),
  Country('US', 'الولايات المتحدة', 'United States', 'États-Unis'),
  Country('UY', 'الأوروغواي', 'Uruguay', 'Uruguay'),
  Country('UZ', 'أوزبكستان', 'Uzbekistan', 'Ouzbékistan'),
  Country('VU', 'فانواتو', 'Vanuatu', 'Vanuatu'),
  Country('VE', 'فنزويلا', 'Venezuela', 'Venezuela'),
  Country('VN', 'فيتنام', 'Vietnam', 'Viêt Nam'),
  Country('ZM', 'زامبيا', 'Zambia', 'Zambie'),
  Country('ZW', 'زيمبابوي', 'Zimbabwe', 'Zimbabwe'),
];
